### PR TITLE
Resolve running `schemaspy:schemaspy` failure

### LINKED ISSUE #705: Running schemaspy:schemaspy fails with NullPointerException
Running `mvn schemaspy:schemaspy` with maven version 3.9.8 fails with a NullPointerException

<details>
<summary>debug info, commandline and stacktrace</summary>

```
"C:\Program Files\Zulu\zulu-17\bin\java.exe" -Dmaven.multiModuleProjectDirectory=C:\Java\projects\intellij\maven\licence\database -Djansi.passthrough=true "-Dmaven.home=C:\Program Files\JetBrains\IntelliJ IDEA 2024.2.4\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\Program Files\JetBrains\IntelliJ IDEA 2024.2.4\plugins\maven\lib\maven3\bin\m2.conf" "-Dmaven.ext.class.path=C:\Program Files\JetBrains\IntelliJ IDEA 2024.2.4\plugins\maven\lib\maven-event-listener.jar" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2024.2.4\lib\idea_rt.jar=54090:C:\Program Files\JetBrains\IntelliJ IDEA 2024.2.4\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA 2024.2.4\plugins\maven\lib\maven3\boot\plexus-classworlds-2.8.0.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2024.2.4\plugins\maven\lib\maven3\boot\plexus-classworlds.license" org.codehaus.classworlds.Launcher -Didea.version=2024.2.4 --debug --update-snapshots -s C:\Users\anonymous\.m2\settings.xml -Dmaven.repo.local=C:\Users\anonymous\.m2\repository schemaspy:schemaspy
Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256)
Maven home: C:\Program Files\JetBrains\IntelliJ IDEA 2024.2.4\plugins\maven\lib\maven3
Java version: 17.0.10, vendor: Azul Systems, Inc., runtime: C:\Program Files\Zulu\zulu-17
Default locale: de_DE, platform encoding: UTF-8
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"
[DEBUG]   Included C:\Program Files\JetBrains\IntelliJ IDEA 2024.2.4\plugins\maven\lib\maven-event-listener.jar
[DEBUG] Populating class realm maven.ext
[DEBUG]   Included C:\Program Files\JetBrains\IntelliJ IDEA 2024.2.4\plugins\maven\lib\maven-event-listener.jar
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: javax.annotation.* < maven.ext
[DEBUG]   Imported: javax.annotation.security.* < maven.ext
[DEBUG]   Imported: javax.inject.* < maven.ext
[DEBUG]   Imported: org.apache.maven.* < maven.ext
[DEBUG]   Imported: org.apache.maven.artifact < maven.ext
[DEBUG]   Imported: org.apache.maven.classrealm < maven.ext
[DEBUG]   Imported: org.apache.maven.cli < maven.ext
[DEBUG]   Imported: org.apache.maven.configuration < maven.ext
[DEBUG]   Imported: org.apache.maven.exception < maven.ext
[DEBUG]   Imported: org.apache.maven.execution < maven.ext
[DEBUG]   Imported: org.apache.maven.execution.scope < maven.ext
[DEBUG]   Imported: org.apache.maven.graph < maven.ext
[DEBUG]   Imported: org.apache.maven.lifecycle < maven.ext
[DEBUG]   Imported: org.apache.maven.model < maven.ext
[DEBUG]   Imported: org.apache.maven.monitor < maven.ext
[DEBUG]   Imported: org.apache.maven.plugin < maven.ext
[DEBUG]   Imported: org.apache.maven.profiles < maven.ext
[DEBUG]   Imported: org.apache.maven.project < maven.ext
[DEBUG]   Imported: org.apache.maven.reporting < maven.ext
[DEBUG]   Imported: org.apache.maven.repository < maven.ext
[DEBUG]   Imported: org.apache.maven.rtinfo < maven.ext
[DEBUG]   Imported: org.apache.maven.settings < maven.ext
[DEBUG]   Imported: org.apache.maven.toolchain < maven.ext
[DEBUG]   Imported: org.apache.maven.usability < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.* < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.authentication < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.authorization < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.events < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.observers < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.proxy < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.repository < maven.ext
[DEBUG]   Imported: org.apache.maven.wagon.resource < maven.ext
[DEBUG]   Imported: org.codehaus.classworlds < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.* < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.classworlds < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.component < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.configuration < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.container < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.context < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.logging < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.personality < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < maven.ext
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < maven.ext
[DEBUG]   Imported: org.eclipse.aether.* < maven.ext
[DEBUG]   Imported: org.eclipse.aether.artifact < maven.ext
[DEBUG]   Imported: org.eclipse.aether.collection < maven.ext
[DEBUG]   Imported: org.eclipse.aether.deployment < maven.ext
[DEBUG]   Imported: org.eclipse.aether.graph < maven.ext
[DEBUG]   Imported: org.eclipse.aether.impl < maven.ext
[DEBUG]   Imported: org.eclipse.aether.installation < maven.ext
[DEBUG]   Imported: org.eclipse.aether.internal.impl < maven.ext
[DEBUG]   Imported: org.eclipse.aether.metadata < maven.ext
[DEBUG]   Imported: org.eclipse.aether.repository < maven.ext
[DEBUG]   Imported: org.eclipse.aether.resolution < maven.ext
[DEBUG]   Imported: org.eclipse.aether.spi < maven.ext
[DEBUG]   Imported: org.eclipse.aether.transfer < maven.ext
[DEBUG]   Imported: org.eclipse.aether.util < maven.ext
[DEBUG]   Imported: org.eclipse.aether.version < maven.ext
[DEBUG]   Imported: org.fusesource.jansi.* < maven.ext
[DEBUG]   Imported: org.slf4j.* < maven.ext
[DEBUG]   Imported: org.slf4j.event.* < maven.ext
[DEBUG]   Imported: org.slf4j.helpers.* < maven.ext
[DEBUG]   Imported: org.slf4j.spi.* < maven.ext
[DEBUG] Populating class realm maven.api
[DEBUG] Created adapter factory; available factories [file-lock, rwlock-local, semaphore-local, noop]; available name mappers [discriminating, file-gav, file-hgav, file-static, gav, static]
[INFO] Error stacktraces are turned on.
[DEBUG] Message scheme: color
[DEBUG] Message styles: debug info warning error success failure strong mojo project
[DEBUG] Reading global settings from C:\Program Files\JetBrains\IntelliJ IDEA 2024.2.4\plugins\maven\lib\maven3\conf\settings.xml
[DEBUG] Reading user settings from C:\Users\anonymous\.m2\settings.xml
[DEBUG] Reading global toolchains from C:\Program Files\JetBrains\IntelliJ IDEA 2024.2.4\plugins\maven\lib\maven3\conf\toolchains.xml
[DEBUG] Reading user toolchains from C:\Users\anonymous\.m2\toolchains.xml
[DEBUG] Using local repository at C:\Users\anonymous\.m2\repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for C:\Users\anonymous\.m2\repository
[INFO] Scanning for projects...
[DEBUG] Using mirror central (http://nexus.company.local:8081/repository/maven-public/) for maven-public (http://nexus.company.local:8081/repository/maven-public/).
[DEBUG] Using mirror official (https://repo.maven.apache.org/maven2/) for central (https://repo.maven.apache.org/maven2/).
[DEBUG] Using mirror archetype (http://nexus.company.local:8081/repository/maven-archetype/) for archetype (http://nexus.company.local:8081/repository/maven-archetypes/).
[DEBUG] Extension realms for project com.company.dbupdate.liquibase:ls:jar:0.0.1-SNAPSHOT: (none)
[DEBUG] Looking up lifecycle mappings for packaging jar from ClassRealm[maven.ext, parent: ClassRealm[plexus.core, parent: null]]
[DEBUG] Resolving plugin prefix schemaspy from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Creating adapter using nameMapper 'gav' and factory 'rwlock-local'
[DEBUG] Using mirror official (https://repo.maven.apache.org/maven2/) for central (https://repo.maven.apache.org/maven2).
[DEBUG] Resolved plugin prefix schemaspy to nl.geodienstencentrum.maven:schemaspy-maven-plugin from POM com.company.dbupdate.liquibase:ls:jar:0.0.1-SNAPSHOT
[DEBUG] === REACTOR BUILD PLAN ================================================
[DEBUG] Project: com.company.dbupdate.liquibase:ls:jar:0.0.1-SNAPSHOT
[DEBUG] Tasks:   [schemaspy:schemaspy]
[DEBUG] Style:   Regular
[DEBUG] =======================================================================
[INFO] 
[INFO] ----------------< com.company.dbupdate.liquibase:ls >----------------
[INFO] Building ls 0.0.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[DEBUG] Resolving plugin prefix schemaspy from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Resolved plugin prefix schemaspy to nl.geodienstencentrum.maven:schemaspy-maven-plugin from POM com.company.dbupdate.liquibase:ls:jar:0.0.1-SNAPSHOT
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] === PROJECT BUILD PLAN ================================================
[DEBUG] Project:       com.company.dbupdate.liquibase:ls:0.0.1-SNAPSHOT
[DEBUG] Dependencies (collect): []
[DEBUG] Dependencies (resolve): []
[DEBUG] Repositories (dependencies): [central (http://nexus.company.local:8081/repository/maven-public/, default, releases+snapshots), official (https://repo.maven.apache.org/maven2/, default, releases+snapshots), archetype (http://nexus.company.local:8081/repository/maven-archetype/, default, snapshots)]
[DEBUG] Repositories (plugins)     : [central (http://nexus.company.local:8081/repository/maven-public/, default, releases+snapshots), official (https://repo.maven.apache.org/maven2/, default, releases)]
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          nl.geodienstencentrum.maven:schemaspy-maven-plugin:5.3.0:schemaspy (default-cli)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <allowHtmlInComments>${allowHtmlInComments}</allowHtmlInComments>
  <catalog default-value="%">${catalog}</catalog>
  <commentsInitiallyDisplayed>${commentsInitiallyDisplayed}</commentsInitiallyDisplayed>
  <connprops>${connprops}</connprops>
  <cssStylesheet>${cssStylesheet}</cssStylesheet>
  <database>lsdb</database>
  <databaseType>pgsql</databaseType>
  <excludeColumnNamesRegex>${excludeColumnNamesRegex}</excludeColumnNamesRegex>
  <highQuality>${highQuality}</highQuality>
  <host>localhost</host>
  <includeTableNamesRegex>${includeTableNamesRegex}</includeTableNamesRegex>
  <inputEncoding default-value="${project.build.sourceEncoding}">${encoding}</inputEncoding>
  <localRepository default-value="${localRepository}"/>
  <logLevel>${logLevel}</logLevel>
  <lowQuality>${lowQuality}</lowQuality>
  <noAds default-value="true">${noAds}</noAds>
  <noHtml>${noHtml}</noHtml>
  <noImplied>${noImplied}</noImplied>
  <noLogo default-value="true">${noLogo}</noLogo>
  <noRows>${noRows}</noRows>
  <noSchema>${noSchema}</noSchema>
  <noViews>${noViews}</noViews>
  <outputDirectory default-value="${project.build.directory}/site">schemaspy/diagram</outputDirectory>
  <outputEncoding default-value="${project.reporting.outputEncoding}">${outputEncoding}</outputEncoding>
  <password>changeit</password>
  <pathToDrivers>C:/Program Files/Java/schemaspy/postgresql-42.7.2.jar</pathToDrivers>
  <port>5432</port>
  <project default-value="${project}"/>
  <remoteRepositories default-value="${project.remoteArtifactRepositories}"/>
  <runOnExecutionRoot default-value="false">${runOnExecutionRoot}</runOnExecutionRoot>
  <schema>ls</schema>
  <schemaDescription>${schemaDescription}</schemaDescription>
  <schemas>${schemas}</schemas>
  <showAllSchemas>${showAllSchemas}</showAllSchemas>
  <singleSignOn>${singleSignOn}</singleSignOn>
  <targetDirectory default-value="${project.build.directory}">${targetDirectory}</targetDirectory>
  <useDriverManager>${useDriverManager}</useDriverManager>
  <user>postgres</user>
  <vizjs default-value="true">${vizjs}</vizjs>
</configuration>
[DEBUG] =======================================================================
[INFO] 
[INFO] --- schemaspy:5.3.0:schemaspy (default-cli) @ ls ---
[DEBUG] Using mirror central (http://nexus.company.local:8081/repository/maven-public/) for apache.snapshots (https://repository.apache.org/snapshots).
[DEBUG] Using mirror central (http://nexus.company.local:8081/repository/maven-public/) for apache.snapshots (http://repository.apache.org/snapshots).
[DEBUG] Using mirror central (http://nexus.company.local:8081/repository/maven-public/) for plexus.snapshots (https://oss.sonatype.org/content/repositories/plexus-snapshots).
[DEBUG] Using mirror central (http://nexus.company.local:8081/repository/maven-public/) for codehaus.snapshots (http://snapshots.repository.codehaus.org).
[DEBUG] Using mirror central (http://nexus.company.local:8081/repository/maven-public/) for sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots).
[DEBUG] Using mirror central (http://nexus.company.local:8081/repository/maven-public/) for repository.jboss.org (http://repository.jboss.org/maven2).
[DEBUG] Using mirror central (http://nexus.company.local:8081/repository/maven-public/) for snapshots.jboss.org (http://snapshots.jboss.org/maven2).
[DEBUG] Using mirror central (http://nexus.company.local:8081/repository/maven-public/) for oss.sonatype.org/jboss-snapshots (http://oss.sonatype.org/content/repositories/jboss-snapshots).
[DEBUG] Using mirror central (http://nexus.company.local:8081/repository/maven-public/) for apache.snapshots (http://people.apache.org/repo/m2-snapshot-repository).
[DEBUG] Using mirror central (http://nexus.company.local:8081/repository/maven-public/) for snapshots (http://snapshots.maven.codehaus.org/maven2).
[DEBUG] Using mirror official (https://repo.maven.apache.org/maven2/) for central (http://repo1.maven.org/maven2).
[DEBUG] Using mirror central (http://nexus.company.local:8081/repository/maven-public/) for ow2-snapshot (http://repository.ow2.org/nexus/content/repositories/snapshots).
[DEBUG] Dependency collection stats {ConflictMarker.analyzeTime=1435500, ConflictMarker.markTime=291000, ConflictMarker.nodeCount=351, ConflictIdSorter.graphTime=954200, ConflictIdSorter.topsortTime=991100, ConflictIdSorter.conflictIdCount=135, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=12424500, ConflictResolver.conflictItemCount=319, DfDependencyCollector.collectTime=777498000, DfDependencyCollector.transformTime=18940400}
[DEBUG] nl.geodienstencentrum.maven:schemaspy-maven-plugin:jar:5.3.0
[DEBUG]    commons-beanutils:commons-beanutils:jar:1.9.4:compile
[DEBUG]       commons-logging:commons-logging:jar:1.2:compile
[DEBUG]       commons-collections:commons-collections:jar:3.2.2:compile
[DEBUG]    org.apache.maven.reporting:maven-reporting-impl:jar:3.2.0:compile
[DEBUG]       org.apache.maven.reporting:maven-reporting-api:jar:3.1.1:compile
[DEBUG]       org.apache.maven:maven-core:jar:3.1.0:compile
[DEBUG]          org.apache.maven:maven-model:jar:3.1.0:compile
[DEBUG]          org.apache.maven:maven-settings:jar:3.1.0:compile
[DEBUG]          org.apache.maven:maven-settings-builder:jar:3.1.0:compile
[DEBUG]          org.apache.maven:maven-repository-metadata:jar:3.1.0:compile
[DEBUG]          org.apache.maven:maven-model-builder:jar:3.1.0:compile
[DEBUG]          org.apache.maven:maven-aether-provider:jar:3.1.0:compile
[DEBUG]             org.eclipse.aether:aether-spi:jar:0.9.0.M2:compile
[DEBUG]          org.eclipse.aether:aether-impl:jar:0.9.0.M2:compile
[DEBUG]          org.eclipse.aether:aether-api:jar:0.9.0.M2:compile
[DEBUG]          org.eclipse.aether:aether-util:jar:0.9.0.M2:compile
[DEBUG]          org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.0.0.M2a:compile
[DEBUG]             javax.enterprise:cdi-api:jar:1.0:compile
[DEBUG]                javax.annotation:jsr250-api:jar:1.0:compile
[DEBUG]                javax.inject:javax.inject:jar:1:compile
[DEBUG]             com.google.guava:guava:jar:10.0.1:compile
[DEBUG]                com.google.code.findbugs:jsr305:jar:1.3.9:compile
[DEBUG]             org.sonatype.sisu:sisu-guice:jar:no_aop:3.1.0:compile
[DEBUG]                aopalliance:aopalliance:jar:1.0:compile
[DEBUG]             org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.0.0.M2a:compile
[DEBUG]                asm:asm:jar:3.3.1:compile
[DEBUG]          org.codehaus.plexus:plexus-interpolation:jar:1.16:compile
[DEBUG]          org.codehaus.plexus:plexus-classworlds:jar:2.4.2:compile
[DEBUG]          org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile
[DEBUG]          org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
[DEBUG]             org.sonatype.plexus:plexus-cipher:jar:1.4:compile
[DEBUG]       org.apache.maven:maven-artifact:jar:3.1.0:compile
[DEBUG]       org.apache.maven:maven-plugin-api:jar:3.1.0:compile
[DEBUG]       org.apache.maven.shared:maven-shared-utils:jar:3.3.4:compile
[DEBUG]       org.apache.maven.doxia:doxia-sink-api:jar:1.11.1:compile
[DEBUG]          org.apache.maven.doxia:doxia-logging-api:jar:1.11.1:compile
[DEBUG]       org.apache.maven.doxia:doxia-decoration-model:jar:1.11.1:compile
[DEBUG]       org.apache.maven.doxia:doxia-core:jar:1.11.1:compile
[DEBUG]          org.codehaus.plexus:plexus-container-default:jar:2.1.0:compile
[DEBUG]             org.apache.xbean:xbean-reflect:jar:3.7:compile
[DEBUG]             com.google.collections:google-collections:jar:1.0:compile
[DEBUG]          org.apache.commons:commons-lang3:jar:3.8.1:compile
[DEBUG]          org.apache.commons:commons-text:jar:1.3:compile
[DEBUG]          org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[DEBUG]             commons-codec:commons-codec:jar:1.11:compile
[DEBUG]          org.apache.httpcomponents:httpcore:jar:4.4.14:compile
[DEBUG]       org.apache.maven.doxia:doxia-integration-tools:jar:1.11.1:compile
[DEBUG]          org.codehaus.plexus:plexus-i18n:jar:1.0-beta-10:compile
[DEBUG]       org.apache.maven.doxia:doxia-site-renderer:jar:1.11.1:compile
[DEBUG]          org.apache.maven.doxia:doxia-skin-model:jar:1.11.1:compile
[DEBUG]          org.apache.maven.doxia:doxia-module-xhtml:jar:1.11.1:compile
[DEBUG]          org.apache.maven.doxia:doxia-module-xhtml5:jar:1.11.1:compile
[DEBUG]          org.codehaus.plexus:plexus-velocity:jar:1.2:compile
[DEBUG]          org.apache.velocity:velocity:jar:1.7:compile
[DEBUG]             commons-lang:commons-lang:jar:2.4:compile
[DEBUG]          org.apache.velocity:velocity-tools:jar:2.0:compile
[DEBUG]             commons-digester:commons-digester:jar:1.8:compile
[DEBUG]             commons-chain:commons-chain:jar:1.1:compile
[DEBUG]             dom4j:dom4j:jar:1.1:compile
[DEBUG]             oro:oro:jar:2.0.8:compile
[DEBUG]       org.codehaus.plexus:plexus-utils:jar:3.3.1:compile
[DEBUG]    org.schemaspy:schemaspy:jar:6.2.4:compile
[DEBUG]       com.github.spullara.mustache.java:compiler:jar:0.9.10:compile
[DEBUG]       commons-io:commons-io:jar:2.7:compile
[DEBUG]       com.vladsch.flexmark:flexmark:jar:0.34.32:compile
[DEBUG]          com.vladsch.flexmark:flexmark-util:jar:0.34.32:compile
[DEBUG]       com.vladsch.flexmark:flexmark-profile-pegdown:jar:0.34.32:compile
[DEBUG]          com.vladsch.flexmark:flexmark-ext-abbreviation:jar:0.34.32:compile
[DEBUG]             com.vladsch.flexmark:flexmark-formatter:jar:0.34.32:compile
[DEBUG]          com.vladsch.flexmark:flexmark-ext-anchorlink:jar:0.34.32:compile
[DEBUG]          com.vladsch.flexmark:flexmark-ext-aside:jar:0.34.32:compile
[DEBUG]             com.vladsch.flexmark:flexmark-jira-converter:jar:0.34.32:compile
[DEBUG]          com.vladsch.flexmark:flexmark-ext-autolink:jar:0.34.32:compile
[DEBUG]             org.nibor.autolink:autolink:jar:0.6.0:compile
[DEBUG]          com.vladsch.flexmark:flexmark-ext-definition:jar:0.34.32:compile
[DEBUG]          com.vladsch.flexmark:flexmark-ext-emoji:jar:0.34.32:compile
[DEBUG]          com.vladsch.flexmark:flexmark-ext-escaped-character:jar:0.34.32:compile
[DEBUG]          com.vladsch.flexmark:flexmark-ext-footnotes:jar:0.34.32:compile
[DEBUG]          com.vladsch.flexmark:flexmark-ext-gfm-strikethrough:jar:0.34.32:compile
[DEBUG]          com.vladsch.flexmark:flexmark-ext-gfm-tasklist:jar:0.34.32:compile
[DEBUG]          com.vladsch.flexmark:flexmark-ext-ins:jar:0.34.32:compile
[DEBUG]          com.vladsch.flexmark:flexmark-ext-jekyll-front-matter:jar:0.34.32:compile
[DEBUG]             com.vladsch.flexmark:flexmark-ext-yaml-front-matter:jar:0.34.32:compile
[DEBUG]          com.vladsch.flexmark:flexmark-ext-superscript:jar:0.34.32:compile
[DEBUG]          com.vladsch.flexmark:flexmark-ext-tables:jar:0.34.32:compile
[DEBUG]          com.vladsch.flexmark:flexmark-ext-toc:jar:0.34.32:compile
[DEBUG]          com.vladsch.flexmark:flexmark-ext-typographic:jar:0.34.32:compile
[DEBUG]          com.vladsch.flexmark:flexmark-ext-wikilink:jar:0.34.32:compile
[DEBUG]       org.json:json:jar:20230227:compile
[DEBUG]       org.springframework.boot:spring-boot-starter:jar:2.2.11.RELEASE:compile
[DEBUG]          org.springframework.boot:spring-boot-starter-logging:jar:2.2.11.RELEASE:compile
[DEBUG]             ch.qos.logback:logback-classic:jar:1.2.3:compile
[DEBUG]                ch.qos.logback:logback-core:jar:1.2.3:compile
[DEBUG]                org.slf4j:slf4j-api:jar:1.7.25:compile
[DEBUG]             org.apache.logging.log4j:log4j-to-slf4j:jar:2.12.1:compile
[DEBUG]                org.apache.logging.log4j:log4j-api:jar:2.12.1:compile
[DEBUG]             org.slf4j:jul-to-slf4j:jar:1.7.30:compile
[DEBUG]          jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[DEBUG]          org.yaml:snakeyaml:jar:1.25:runtime
[DEBUG]       org.springframework.boot:spring-boot:jar:2.2.11.RELEASE:compile
[DEBUG]       org.springframework.boot:spring-boot-autoconfigure:jar:2.2.11.RELEASE:compile
[DEBUG]       org.springframework:spring-core:jar:5.2.10.RELEASE:compile
[DEBUG]          org.springframework:spring-jcl:jar:5.2.10.RELEASE:compile
[DEBUG]       org.springframework:spring-context:jar:5.2.10.RELEASE:compile
[DEBUG]          org.springframework:spring-aop:jar:5.2.10.RELEASE:compile
[DEBUG]          org.springframework:spring-expression:jar:5.2.10.RELEASE:compile
[DEBUG]       org.springframework:spring-beans:jar:5.2.10.RELEASE:compile
[DEBUG]       org.hamcrest:hamcrest-core:jar:2.1:compile
[DEBUG]          org.hamcrest:hamcrest:jar:2.1:compile
[DEBUG]       com.beust:jcommander:jar:1.69:compile
[DEBUG]       xalan:xalan:jar:2.7.2:compile
[DEBUG]          xalan:serializer:jar:2.7.2:compile
[DEBUG]             xml-apis:xml-apis:jar:1.3.04:compile
[DEBUG]       org.openjdk.nashorn:nashorn-core:jar:15.4:compile
[DEBUG]          org.ow2.asm:asm:jar:7.3.1:compile
[DEBUG]          org.ow2.asm:asm-commons:jar:7.3.1:compile
[DEBUG]             org.ow2.asm:asm-analysis:jar:7.3.1:compile
[DEBUG]          org.ow2.asm:asm-tree:jar:7.3.1:compile
[DEBUG]          org.ow2.asm:asm-util:jar:7.3.1:compile
[DEBUG]    org.apache.derby:derby:jar:10.15.2.0:compile (optional)
[DEBUG]       org.apache.derby:derbyshared:jar:10.15.2.0:compile (optional)
[DEBUG]    org.apache.derby:derbytools:jar:10.15.2.0:compile (optional)
[DEBUG]    org.hsqldb:hsqldb:jar:2.7.3:compile (optional)
[DEBUG]    org.postgresql:postgresql:jar:42.7.4:compile (optional)
[DEBUG]       org.checkerframework:checker-qual:jar:3.42.0:runtime (optional)
[DEBUG]    com.microsoft.sqlserver:mssql-jdbc:jar:12.8.1.jre11:compile (optional)
[DEBUG]    com.mysql:mysql-connector-j:jar:9.0.0:compile (optional)
[DEBUG]       com.google.protobuf:protobuf-java:jar:4.26.1:compile (optional)
[DEBUG]    com.oracle.database.jdbc:ojdbc11:jar:23.5.0.24.07:compile (optional)
[DEBUG] Created new class realm plugin>nl.geodienstencentrum.maven:schemaspy-maven-plugin:5.3.0
[DEBUG] Importing foreign packages into class realm plugin>nl.geodienstencentrum.maven:schemaspy-maven-plugin:5.3.0
[DEBUG]   Imported:  < maven.api
[DEBUG] Populating class realm plugin>nl.geodienstencentrum.maven:schemaspy-maven-plugin:5.3.0
[DEBUG]   Included: nl.geodienstencentrum.maven:schemaspy-maven-plugin:jar:5.3.0
[DEBUG]   Included: commons-beanutils:commons-beanutils:jar:1.9.4
[DEBUG]   Included: commons-logging:commons-logging:jar:1.2
[DEBUG]   Included: commons-collections:commons-collections:jar:3.2.2
[DEBUG]   Included: org.apache.maven.reporting:maven-reporting-impl:jar:3.2.0
[DEBUG]   Included: org.apache.maven.reporting:maven-reporting-api:jar:3.1.1
[DEBUG]   Included: javax.enterprise:cdi-api:jar:1.0
[DEBUG]   Included: javax.annotation:jsr250-api:jar:1.0
[DEBUG]   Included: com.google.guava:guava:jar:10.0.1
[DEBUG]   Included: com.google.code.findbugs:jsr305:jar:1.3.9
[DEBUG]   Included: org.sonatype.sisu:sisu-guice:jar:no_aop:3.1.0
[DEBUG]   Included: aopalliance:aopalliance:jar:1.0
[DEBUG]   Included: org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.0.0.M2a
[DEBUG]   Included: asm:asm:jar:3.3.1
[DEBUG]   Included: org.codehaus.plexus:plexus-interpolation:jar:1.16
[DEBUG]   Included: org.codehaus.plexus:plexus-component-annotations:jar:1.5.5
[DEBUG]   Included: org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3
[DEBUG]   Included: org.sonatype.plexus:plexus-cipher:jar:1.4
[DEBUG]   Included: org.apache.maven.shared:maven-shared-utils:jar:3.3.4
[DEBUG]   Included: org.apache.maven.doxia:doxia-sink-api:jar:1.11.1
[DEBUG]   Included: org.apache.maven.doxia:doxia-logging-api:jar:1.11.1
[DEBUG]   Included: org.apache.maven.doxia:doxia-decoration-model:jar:1.11.1
[DEBUG]   Included: org.apache.maven.doxia:doxia-core:jar:1.11.1
[DEBUG]   Included: org.apache.xbean:xbean-reflect:jar:3.7
[DEBUG]   Included: com.google.collections:google-collections:jar:1.0
[DEBUG]   Included: org.apache.commons:commons-lang3:jar:3.8.1
[DEBUG]   Included: org.apache.commons:commons-text:jar:1.3
[DEBUG]   Included: org.apache.httpcomponents:httpclient:jar:4.5.13
[DEBUG]   Included: commons-codec:commons-codec:jar:1.11
[DEBUG]   Included: org.apache.httpcomponents:httpcore:jar:4.4.14
[DEBUG]   Included: org.apache.maven.doxia:doxia-integration-tools:jar:1.11.1
[DEBUG]   Included: org.codehaus.plexus:plexus-i18n:jar:1.0-beta-10
[DEBUG]   Included: org.apache.maven.doxia:doxia-site-renderer:jar:1.11.1
[DEBUG]   Included: org.apache.maven.doxia:doxia-skin-model:jar:1.11.1
[DEBUG]   Included: org.apache.maven.doxia:doxia-module-xhtml:jar:1.11.1
[DEBUG]   Included: org.apache.maven.doxia:doxia-module-xhtml5:jar:1.11.1
[DEBUG]   Included: org.codehaus.plexus:plexus-velocity:jar:1.2
[DEBUG]   Included: org.apache.velocity:velocity:jar:1.7
[DEBUG]   Included: commons-lang:commons-lang:jar:2.4
[DEBUG]   Included: org.apache.velocity:velocity-tools:jar:2.0
[DEBUG]   Included: commons-digester:commons-digester:jar:1.8
[DEBUG]   Included: commons-chain:commons-chain:jar:1.1
[DEBUG]   Included: dom4j:dom4j:jar:1.1
[DEBUG]   Included: oro:oro:jar:2.0.8
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:3.3.1
[DEBUG]   Included: org.schemaspy:schemaspy:jar:6.2.4
[DEBUG]   Included: com.github.spullara.mustache.java:compiler:jar:0.9.10
[DEBUG]   Included: commons-io:commons-io:jar:2.7
[DEBUG]   Included: com.vladsch.flexmark:flexmark:jar:0.34.32
[DEBUG]   Included: com.vladsch.flexmark:flexmark-util:jar:0.34.32
[DEBUG]   Included: com.vladsch.flexmark:flexmark-profile-pegdown:jar:0.34.32
[DEBUG]   Included: com.vladsch.flexmark:flexmark-ext-abbreviation:jar:0.34.32
[DEBUG]   Included: com.vladsch.flexmark:flexmark-formatter:jar:0.34.32
[DEBUG]   Included: com.vladsch.flexmark:flexmark-ext-anchorlink:jar:0.34.32
[DEBUG]   Included: com.vladsch.flexmark:flexmark-ext-aside:jar:0.34.32
[DEBUG]   Included: com.vladsch.flexmark:flexmark-jira-converter:jar:0.34.32
[DEBUG]   Included: com.vladsch.flexmark:flexmark-ext-autolink:jar:0.34.32
[DEBUG]   Included: org.nibor.autolink:autolink:jar:0.6.0
[DEBUG]   Included: com.vladsch.flexmark:flexmark-ext-definition:jar:0.34.32
[DEBUG]   Included: com.vladsch.flexmark:flexmark-ext-emoji:jar:0.34.32
[DEBUG]   Included: com.vladsch.flexmark:flexmark-ext-escaped-character:jar:0.34.32
[DEBUG]   Included: com.vladsch.flexmark:flexmark-ext-footnotes:jar:0.34.32
[DEBUG]   Included: com.vladsch.flexmark:flexmark-ext-gfm-strikethrough:jar:0.34.32
[DEBUG]   Included: com.vladsch.flexmark:flexmark-ext-gfm-tasklist:jar:0.34.32
[DEBUG]   Included: com.vladsch.flexmark:flexmark-ext-ins:jar:0.34.32
[DEBUG]   Included: com.vladsch.flexmark:flexmark-ext-jekyll-front-matter:jar:0.34.32
[DEBUG]   Included: com.vladsch.flexmark:flexmark-ext-yaml-front-matter:jar:0.34.32
[DEBUG]   Included: com.vladsch.flexmark:flexmark-ext-superscript:jar:0.34.32
[DEBUG]   Included: com.vladsch.flexmark:flexmark-ext-tables:jar:0.34.32
[DEBUG]   Included: com.vladsch.flexmark:flexmark-ext-toc:jar:0.34.32
[DEBUG]   Included: com.vladsch.flexmark:flexmark-ext-typographic:jar:0.34.32
[DEBUG]   Included: com.vladsch.flexmark:flexmark-ext-wikilink:jar:0.34.32
[DEBUG]   Included: org.json:json:jar:20230227
[DEBUG]   Included: org.springframework.boot:spring-boot-starter:jar:2.2.11.RELEASE
[DEBUG]   Included: org.springframework.boot:spring-boot-starter-logging:jar:2.2.11.RELEASE
[DEBUG]   Included: ch.qos.logback:logback-classic:jar:1.2.3
[DEBUG]   Included: ch.qos.logback:logback-core:jar:1.2.3
[DEBUG]   Included: org.apache.logging.log4j:log4j-to-slf4j:jar:2.12.1
[DEBUG]   Included: org.apache.logging.log4j:log4j-api:jar:2.12.1
[DEBUG]   Included: org.slf4j:jul-to-slf4j:jar:1.7.30
[DEBUG]   Included: jakarta.annotation:jakarta.annotation-api:jar:1.3.5
[DEBUG]   Included: org.yaml:snakeyaml:jar:1.25
[DEBUG]   Included: org.springframework.boot:spring-boot:jar:2.2.11.RELEASE
[DEBUG]   Included: org.springframework.boot:spring-boot-autoconfigure:jar:2.2.11.RELEASE
[DEBUG]   Included: org.springframework:spring-core:jar:5.2.10.RELEASE
[DEBUG]   Included: org.springframework:spring-jcl:jar:5.2.10.RELEASE
[DEBUG]   Included: org.springframework:spring-context:jar:5.2.10.RELEASE
[DEBUG]   Included: org.springframework:spring-aop:jar:5.2.10.RELEASE
[DEBUG]   Included: org.springframework:spring-expression:jar:5.2.10.RELEASE
[DEBUG]   Included: org.springframework:spring-beans:jar:5.2.10.RELEASE
[DEBUG]   Included: org.hamcrest:hamcrest-core:jar:2.1
[DEBUG]   Included: org.hamcrest:hamcrest:jar:2.1
[DEBUG]   Included: com.beust:jcommander:jar:1.69
[DEBUG]   Included: xalan:xalan:jar:2.7.2
[DEBUG]   Included: xalan:serializer:jar:2.7.2
[DEBUG]   Included: xml-apis:xml-apis:jar:1.3.04
[DEBUG]   Included: org.openjdk.nashorn:nashorn-core:jar:15.4
[DEBUG]   Included: org.ow2.asm:asm:jar:7.3.1
[DEBUG]   Included: org.ow2.asm:asm-commons:jar:7.3.1
[DEBUG]   Included: org.ow2.asm:asm-analysis:jar:7.3.1
[DEBUG]   Included: org.ow2.asm:asm-tree:jar:7.3.1
[DEBUG]   Included: org.ow2.asm:asm-util:jar:7.3.1
[DEBUG]   Included: org.apache.derby:derby:jar:10.15.2.0
[DEBUG]   Included: org.apache.derby:derbyshared:jar:10.15.2.0
[DEBUG]   Included: org.apache.derby:derbytools:jar:10.15.2.0
[DEBUG]   Included: org.hsqldb:hsqldb:jar:2.7.3
[DEBUG]   Included: org.postgresql:postgresql:jar:42.7.4
[DEBUG]   Included: org.checkerframework:checker-qual:jar:3.42.0
[DEBUG]   Included: com.microsoft.sqlserver:mssql-jdbc:jar:12.8.1.jre11
[DEBUG]   Included: com.mysql:mysql-connector-j:jar:9.0.0
[DEBUG]   Included: com.google.protobuf:protobuf-java:jar:4.26.1
[DEBUG]   Included: com.oracle.database.jdbc:ojdbc11:jar:23.5.0.24.07
[DEBUG] Loading mojo nl.geodienstencentrum.maven:schemaspy-maven-plugin:5.3.0:schemaspy from plugin realm ClassRealm[plugin>nl.geodienstencentrum.maven:schemaspy-maven-plugin:5.3.0, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@60e53b93]
[DEBUG] Setting property: velocimacro.permissions.allow.inline.to.replace.global => 'true'.
[DEBUG] Setting property: eventhandler.include.class => 'org.apache.velocity.app.event.implement.IncludeRelativePath'.
[DEBUG] Setting property: velocimacro.messages.on => 'false'.
[DEBUG] Setting property: file.resource.loader.path => ''.
[DEBUG] Setting property: resource.loader => 'classpath,file'.
[DEBUG] Setting property: file.resource.loader.class => 'org.apache.velocity.runtime.resource.loader.FileResourceLoader'.
[DEBUG] Setting property: runtime.log.invalid.references => 'false'.
[DEBUG] Setting property: resource.manager.logwhenfound => 'false'.
[DEBUG] Setting property: classpath.resource.loader.class => 'org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader'.
[DEBUG] Initializing Velocity, Calling init()...
[DEBUG] *******************************************************************
[DEBUG] Starting Apache Velocity v1.7 (compiled: 2010-11-19 12:14:37)
[DEBUG] RuntimeInstance initializing.
[DEBUG] Default Properties File: org\apache\velocity\runtime\defaults\velocity.properties
[DEBUG] Default ResourceManager initializing. (class org.apache.velocity.runtime.resource.ResourceManagerImpl)
[DEBUG] ResourceLoader instantiated: org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader
[DEBUG] ClasspathResourceLoader : initialization complete.
[DEBUG] ResourceLoader instantiated: org.apache.velocity.runtime.resource.loader.FileResourceLoader
[DEBUG] FileResourceLoader : initialization starting.
[DEBUG] Do unicode file recognition:  false
[DEBUG] FileResourceLoader : adding path ''
[DEBUG] FileResourceLoader : initialization complete.
[DEBUG] ResourceCache: initialized (class org.apache.velocity.runtime.resource.ResourceCacheImpl) with class java.util.Collections$SynchronizedMap cache map.
[DEBUG] Default ResourceManager initialization complete.
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Stop
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Define
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Break
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Evaluate
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Literal
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Macro
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Parse
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Include
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Foreach
[DEBUG] Created '20' parsers.
[DEBUG] Velocimacro : initialization starting.
[DEBUG] Velocimacro : allowInline = true : VMs can be defined inline in templates
[DEBUG] Velocimacro : allowInlineToOverride = true : VMs defined inline may replace previous VM definitions
[DEBUG] Velocimacro : allowInlineLocal = false : VMs defined inline will be global in scope if allowed.
[DEBUG] Velocimacro : autoload off : VM system will not automatically reload global library macros
[DEBUG] Velocimacro : Velocimacro : initialization complete.
[DEBUG] RuntimeInstance successfully initialized.
[DEBUG] Configuring mojo execution 'nl.geodienstencentrum.maven:schemaspy-maven-plugin:5.3.0:schemaspy:default-cli' with basic configurator -->
[DEBUG]   (f) catalog = %
[DEBUG]   (f) database = lsdb
[DEBUG]   (f) databaseType = pgsql
[DEBUG]   (f) host = localhost
[DEBUG]   (f) localRepository =       id: local
      url: file:///C:/Users/anonymous/.m2/repository/
   layout: default
snapshots: [enabled => true, update => always]
 releases: [enabled => true, update => always]
   blocked: false

[DEBUG]   (f) noAds = true
[DEBUG]   (f) noLogo = true
[DEBUG]   (f) outputDirectory = schemaspy/diagram
[DEBUG]   (f) password = changeit
[DEBUG]   (f) pathToDrivers = C:/Program Files/Java/schemaspy/postgresql-42.7.2.jar
[DEBUG]   (f) port = 5432
[DEBUG]   (f) project = MavenProject: com.company.dbupdate.liquibase:ls:0.0.1-SNAPSHOT @ C:\Java\projects\intellij\maven\licence\database\pom.xml
[DEBUG]   (f) remoteRepositories = [      id: central
      url: http://nexus.company.local:8081/repository/maven-public/
   layout: default
snapshots: [enabled => true, update => always]
 releases: [enabled => true, update => daily]
   blocked: false
,       id: official
      url: https://repo.maven.apache.org/maven2/
   layout: default
    proxy: 192.168.9.2:3128
snapshots: [enabled => true, update => daily]
 releases: [enabled => true, update => daily]
   blocked: false
,       id: archetype
      url: http://nexus.company.local:8081/repository/maven-archetype/
   layout: default
snapshots: [enabled => true, update => daily]
 releases: [enabled => false, update => daily]
   blocked: false
]
[DEBUG]   (f) runOnExecutionRoot = false
[DEBUG]   (f) schema = ls
[DEBUG]   (f) targetDirectory = C:\Java\projects\intellij\maven\licence\database\target
[DEBUG]   (f) user = postgres
[DEBUG]   (f) vizjs = true
[DEBUG] -- end configuration --
[INFO] Rendering content with org.apache.maven.skins:maven-default-skin:jar:1.3 skin.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.487 s
[INFO] Finished at: 2025-01-15T10:06:44+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal nl.geodienstencentrum.maven:schemaspy-maven-plugin:5.3.0:schemaspy (default-cli) on project ls: Execution default-cli of goal nl.geodienstencentrum.maven:schemaspy-maven-plugin:5.3.0:schemaspy failed: Cannot invoke "org.apache.maven.project.MavenProject.getName()" because "this.project" is null -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal nl.geodienstencentrum.maven:schemaspy-maven-plugin:5.3.0:schemaspy (default-cli) on project ls: Execution default-cli of goal nl.geodienstencentrum.maven:schemaspy-maven-plugin:5.3.0:schemaspy failed: Cannot invoke "org.apache.maven.project.MavenProject.getName()" because "this.project" is null
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:333)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:903)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:280)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:203)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:41)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal nl.geodienstencentrum.maven:schemaspy-maven-plugin:5.3.0:schemaspy failed: Cannot invoke "org.apache.maven.project.MavenProject.getName()" because "this.project" is null
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:133)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:903)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:280)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:203)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:41)
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.maven.project.MavenProject.getName()" because "this.project" is null
    at org.apache.maven.reporting.AbstractMavenReport.createSiteRenderingContext (AbstractMavenReport.java:218)
    at org.apache.maven.reporting.AbstractMavenReport.execute (AbstractMavenReport.java:156)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:903)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:280)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:203)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:41)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[DEBUG] Shutting down adapter factory; available factories [file-lock, rwlock-local, semaphore-local, noop]; available name mappers [discriminating, file-gav, file-hgav, file-static, gav, static]
[DEBUG] Shutting down 'file-lock' factory
[DEBUG] Shutting down 'rwlock-local' factory
[DEBUG] Shutting down 'semaphore-local' factory
[DEBUG] Shutting down 'noop' factory

Process finished with exit code 1
```
</details>

### PR DESCRIPTION
**Pull request by mprins**
- [x] Add testcase for `default-cli` this should demonstrate #705
- [x] Remove overridden properties that prevent `default-cli` usage, close #705

### CODE REVIEW

File: src/main/java/com/wakaleo/schemaspy/SchemaSpyReport.java [hunk 1]
```diff
@@ -1,513 +1,401 @@
...
-     *
-     */
-    @Parameter(property = "outputDirectory", defaultValue = "${project.build.directory}/site")
-    private String outputDirectory;
-
-    /**
-     * Site rendering component for generating the HTML report.
-     */
-    @Component
-    private Renderer siteRenderer;
```
Comment (omarmahamid) [inline src/main/java/com/wakaleo/schemaspy/SchemaSpyReport.java:55]: So how works before?
